### ISSUE TITLE
Error from PCRE library in PHP on startup

### ISSUE THREAD

**Issue by Danack** [oerdnj/deb.sury.org#1682]
**Frequently asked questions**

- [X] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)

**Errors apparently from PCRE library**

I'm getting slightly odd error messages that are apparently coming from the PCRE library:

```
PHP Startup: ^(text/|application/xhtml\+xml) (offset=0): unrecognised compile-time option bit(s) in Unknown on line 0
```

**To Reproduce**

This can be reproduced by building and running the following docker container.

```
FROM debian:10-slim

USER root

# Get Debian up-to-date
RUN apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y git \
    mariadb-client wget curl unzip \
    ca-certificates lsb-release apt-transport-https gnupg


# Install 3rd party PHP 8.0 packages
RUN echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | tee -a /etc/apt/sources.list.d/php.list

RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg

RUN  apt-get update -qq \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y php8.0 php8.0-common php8.0-cli \
    php8.0-mysql php8.0-curl php8.0-xml php8.0-mbstring \
    php8.0-intl php8.0-redis php8.0-zip unzip

# Make the default directory you
WORKDIR /var/app

CMD php -v
```

This gives output that includes ` | PHP Warning:  PHP Startup: ^(text/|application/xhtml\+xml) (offset=0): unrecognised compile-time option bit(s) in Unknown on line 0`

Disabling mbstring makes the problem "go away", but I'm also seeing the problem with userland regexes from symfony/console.

**Expected behavior**

No error message.

**Distribution (please complete the following information):**
 - OS:debian
 - Architecture: not sure.
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
Output of `apt-cache policy <package>` works best.

**Additional context**
This only started happening recently, like the last few days or maybe week.

New container build that is showing this problem.
```
PCRE (Perl Compatible Regular Expressions) Support => enabled
PCRE Library Version => 10.32 2018-09-10
PCRE Unicode Version => 11.0.0
PCRE JIT Support => enabled
PCRE JIT Target => x86 64bit (little endian + unaligned)
```

Old container, built over a week ago that is not showing this problem

```
PCRE (Perl Compatible Regular Expressions) Support	enabled
PCRE Library Version	10.39 2021-10-29
PCRE Unicode Version	14.0.0
PCRE JIT Support	enabled
PCRE JIT Target	x86 64bit (little endian + unaligned)
```

**Comment by calvera** [comment]
it work if you do apt-get dist-upgrade before php installation

**Comment by Danack** [comment]
possibly related - https://bugs.php.net/bug.php?id=81424

**Comment by luispabon** [comment]
Affected versions:
 * 7.4.26
 * 8.0.12

Unaffected: 7.3.33

**Comment by Danack** [comment]
@calvera - thanks, can confirm that adding a dist-upgrade makes the issue go away. 

```
RUN  apt-get update -qq && \
     apt-get dist-upgrade -y && \
     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y php8.0 php8.0-common php8.0-cli \
     php8.0-mysql php8.0-curl php8.0-xml php8.0-mbstring \
     php8.0-intl php8.0-redis php8.0-zip unzip
```

I will let Mr Surý decide whether to close this issue or not.

**Comment by zerodeux** [comment]
I have the exact same bug with PHP-7.4 on Debian 10 when going from 7.4.25-2+0~20211101.54+debian10~1.gbp484212 to 7.4.26-1+0~20211119.55+debian10~1.gbpf9fa11, reproduced on several servers with Wordpress and Symfony-based apps, REs that did work before without warnings suddenly fail.

It seems to happen because those servers keep Debian's libpcre2 :
```
||/ Name               Version      Architecture Description
+++-==================-============-============-===================================================================
ii  libpcre2-8-0:amd64 10.32-5      amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
```

But it should upgrade to deb.sury.org's libpcre2 :
```
||/ Name               Version                                    Architecture Description
+++-==================-==========================================-============-===================================================================
ii  libpcre2-8-0:amd64 10.39-1+0~20211102.13+debian10~1.gbp2315ad amd64        New Perl Compatible Regular Expression Library- 8 bit runtime files
```

In my case it's by design, I have pinned deb.sury.org Pacakges (via /etc/apt/preferences.d) in order not to pull dependencies from this repo as a default. But it's my fault it's not working if I don't let in the compatible libpcre2 from deb.sury.org.

**Comment by luispabon** [comment]
dist-upgrade brings in newer libs, including pcre, from Ondrej's PPA, which when installed fix the problem.

**Comment by cmb69** [comment]
I think this is caused by https://github.com/php/php-src/pull/7602, in combination with some pcre.h confusion (bundled vs. system). Not sure whether that is a distro issue or a general issue of php-src. Anyway, upstream ticket is https://bugs.php.net/bug.php?id=81640.

**Comment by shivammathur** [comment]
@oerdnj I think increasing the minimum `libpcre2-dev` version to the latest release in the control file would be a good solution.

**Comment by rfay** [comment]
I would be really appreciative if this could be solved without change to existing installations, because it breaks lots of ddev instances already in the wild. I'm happy to add the dist-upgrade to the code that generates the changes, but that won't solve the problem for existing people.

Interesting factoid: this isn't an issue on arm64, only on amd64. 

Second interesting factoid: Causes a flaming crash in `composer self-update` (php7.4, amd64). `sudo apt-get update && sudo apt-get install php7.4-tidy, which forces several other upgrades... then

```
root@ba32d083e588:/# composer self-update
PHP Fatal error:  Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:137
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'preg_match_all(...', 'phar:///usr/loc...', 137, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php(137): preg_match_all('#<(([a-z][a-z0-...', '', NULL, 256)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(155): Symfony\Component\Console\Formatter\OutputFormatter->format('')
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write(Array, true, 16)
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln('', 16)
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 137

Fatal error: Uncaught ErrorException: preg_match_all(): Compilation failed: unrecognised compile-time option bit(s) at offset 0 in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php:137
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'preg_match_all(...', 'phar:///usr/loc...', 137, Array)
#1 phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php(137): preg_match_all('#<(([a-z][a-z0-...', '', NULL, 256)
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(155): Symfony\Component\Console\Formatter\OutputFormatter->format('')
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Output/Output.php(132): Symfony\Component\Console\Output\Output->write(Array, true, 16)
#4 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(641): Symfony\Component\Console\Output\Output->writeln('', 16)
#5 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application in phar:///usr/local/bin/composer/vendor/symfony/console/Formatter/OutputFormatter.php on line 137
root@ba32d083e588:/# 
```

**Comment by swarrenwecareconnectorg** [comment]
@shivammathur, adding `libpcre2-dev` to my `apt-get install` is what fixed it for me!  Thanks!

**Comment by oerdnj** [comment]
> @oerdnj I think increasing the minimum `libpcre2-dev` version to the latest release in the control file would be a good solution.

No, that's not going to work. The `libpcre2-8-0` package is independent on the development library package.

**Comment by peterdd** [comment]
I applied the workaround for a Vagrantfile to make latest PHP 7.4.26 working.

```ruby
Vagrant.configure("2") do |config|
 config.vm.box = "debian/buster64"
 config.vm.network "private_network", ip: "10.0.0.74"
 config.vm.hostname = "deb10-php74.local"

 config.vm.provision "shell", inline: <<-SHELL
        wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
        echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
        apt-get update

        # temporary workaround for https://github.com/oerdnj/deb.sury.org/issues/1682
        apt-get install -y libpcre2-dev

        apt-get install -y curl unzip mariadb-server apache2
        apt-get install -y php7.4 php7.4-mbstring php7.4-curl php7.4-xml php7.4-gd php7.4-mysql

        a2enmod php7.4
        # restart also to enable php extensions that were installed after apache2 package
        systemctl restart apache2

        ...
        # app testing stuff (get app sourcecode, run composer)

SHELL
end
```

**Comment by Igor-Yavych** [comment]
On debian buster (-slim), simply running  `apt-get upgrade -y` will suffice as it will update libpcre2-8-0 to 10.39-1 and libpcre3 to 2:8.44 from sury.org repo

**Comment by ohmydevops** [comment]
I have the same problem with our ci/cd pipelines today.

I fixed the problem according to the recommendations:

![image](https://user-images.githubusercontent.com/21690865/142758199-4e47fb14-52de-4987-9f4a-045501bef68a.png)

`RUN apt-get install --no-install-recommends --yes libpcre2-dev`

**Comment by oerdnj** [comment]
FTR installing `libpcre2-dev` is wrong and definitely not recommended solution. You need to actually upgrade all the packages instead of randomly installing development libraries. I am going to delete all comments that recommend installing `libpcre2-dev` now.

**Comment by ohmydevops** [comment]
> FTR installing `libpcre2-dev` is wrong and definitely not recommended solution. You need to actually upgrade all the packages instead of randomly installing development libraries. I am going to delete all comments that recommend installing `libpcre2-dev` now.

@oerdnj 

- What do you think about this solution? https://github.com/composer/composer/issues/10294#issuecomment-974318785
- Is it good to write an apt-get upgrade command in Dockerfiles?

**Comment by oerdnj** [comment]
> Is it good to write an apt-get upgrade command in Dockerfiles?

This is a bare minimum. You should be doing `apt-get dist-upgrade` otherwise you are running random mix of updated and outdated packages.

**Comment by miketimofeev** [comment]
This also broke GH-hosted images generation in https://github.com/actions/virtual-environments.
We have made a PR with libpcre2 upgrade as workaround to the issue https://github.com/actions/virtual-environments/pull/4551

**Comment by oerdnj** [comment]
> I think this is caused by [php/php-src#7602](https://github.com/php/php-src/pull/7602)

Yes, see https://github.com/PhilipHazel/pcre2/issues/56

> in combination with some pcre.h confusion (bundled vs. system).

Nope, using different compile-time and run-time system library is all that's needed to trigger this.

> Not sure whether that is a distro issue or a general issue of php-src. Anyway, upstream ticket is https://bugs.php.net/bug.php?id=81640.

I think this needs workaround at the distro level. Generally speaking, the problem lies in the fact that the newly added option is header only and not symbol, so there's no way how to track backwards compatibility. This will require some manual tweaking to the Debian packaging. I already applied the change to the DEB.SURY.ORG `src:pcre2`, but the same problem plagues vanilla Debian, so I already suggested a fix to Matthew Vernon, the maintainer of `src:pcre2`. Basically, same bump in the minimal version will be needed every time there's a change in options in the header file.

**Comment by oerdnj** [comment]
Newly rebuilt packages should already contain `libpcre2-8-0 (>= 10.38)` in `Depends`, closing.

**Comment by rfay** [comment]
This doesn't seem to have made it to Debian arm64 yet, although working on Debian amd64. Thanks for the fix, hope it will propagate everywhere soon.

**Comment by oerdnj** [comment]
TBH I didn't wait for pcre2 to be built on all archs, so this will get fixed with the next package update.

**Comment by rfay** [comment]
Thanks, and as always thanks for these packages. 

Sooner package update is better because existing projects on arm64 are affected by this and there's no way to workaround that I've thought of. I did already add the dist-upgrade as standard though, so future situations wouldn't be affected by this (after next ddev release).
